[build]
# target = "aarch64-unknown-none-softfloat"
# target = "x86_64-unknown-none"
# target = "riscv64imac-unknown-none-elf"
target = "loongarch64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    '-Clink-arg=-no-pie',
]

# Please set the mock environment here.
# For developing.
[env]
KERNEL_OFFSET = "0"
PAGE_SIZE = "4096"